### ISSUE TITLE
License project checklist

### ISSUE THREAD

**Issue by gentooza** [aulasoftwarelibre/Rx-Flappy#1]
what do we need to license the project?

- [x] Organization proposal (un poquito de organización!)

**GPLv3+ work**
- [x] Define Copyright holder, License notice and whole license header (#5)
- [ ] Add a basic README file (#2)
- [x] Add License COPYING (#3)
- [ ] Add license headers in markdown files
- [x] Add license headers in *.js files
- [ ] Add license headers in *.json files
- [x] Add license headers in *.css files
- [ ] Add license headers in *.ts files
- [x] Add license headers in *.html files
- [ ] Add license for images (or look for alternatives).
- [ ] Add license for fonts (or look for alternatives).
- [ ] Add license headers in .prettierrc file. (or remove if not needed)
- [ ] Add license headers in .editorconfig file. (or remove if not needed)

**Apache2 work**
- [ ] what we need to license it as Apache2? (#10)

**Comment by p52safer** [comment]
@gentooza I propose to add the following file types to the list of issue #1 , in order to cross off items little by little

* [ ] Add license headers in `*.json` files
* [ ] Add license headers in `*.png` files
* [ ] Add license headers in `*.jpg` files
* [ ] Add license headers in `*.ttf` files
* [ ] Add license headers in `*.ico` files
* [x] Add license headers in `*.css` files
* [ ] Add license headers in `*.ts` files
* [x] Add license headers in `*.html` files

I am not sure if it is necessary to license these files:

* [ ] Add license headers in `.prettierrc` file
* [ ] Add license headers in `.editorconfig` file

**Comment by gentooza** [comment]
cool, merged.

As .ico, .jpg and .png files are binaries (images) we can left them in a final step about licensing images.
 
- [ ] Add license for images.

As ttf are fonts files, also binaries, we can add:

- [ ] Add license for fonts.

is it ok?

**Comment by gentooza** [comment]
> I am not sure if it is necessary to license these files:
> 
> - [ ] Add license headers in .prettierrc file
> - [ ] Add license headers in .editorconfig file

Yes! We have to license everything needed for running the app. (Although if this files are not really necessary we can remove them from repository)

**Comment by p52safer** [comment]
Ok, perfect!

**Comment by p52safer** [comment]
@gentooza I just made a pull request (pull request #8 ). We can cross out the *.js, *.css and *.html elements from the TODO list if everything is OK.

**Comment by gentooza** [comment]
Sorry @p52safer ! I said nothing, your work is perfect and merged now in the _gplv3_ branch!
